name: ci

on: 
  workflow_dispatch:
  pull_request:
    tags-ignore:
      - '**'
    paths-ignore:
      - "**.md"
      - ".gitignore"      
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/maplibre/android-ndk-r21b

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check code style
        run: make checkstyle

      - name: Check codenarc code style
        run: make codenarc

      - name: Run unit-test
        run: make test   

      - name: Build test plugin
        run: make release
