name: release

on: 
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - "**.md"
      - ".gitignore"   
  
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/maplibre/android-ndk-r21b

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check code style
        run: make checkstyle

      - name: Check codenarc code style
        run: make codenarc

      - name: Run unit-test
        run: make test   

      - name: Build test plugin
        run: make release

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME_TOKEN }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD_TOKEN }}

      # - name: Set up Java for publishing to GitHub Packages
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      # - name: Publish to GitHub Packages
      #   run: mvn --batch-mode deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Prepare MavenCentral release
      #   env:
      #     GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
      #   run: |
      #     echo "${GPG_KEY_CONTENTS}" | base64 -d > signing-key.gpg
      #   shell: bash

      # - name: Publish to MavenCentral
      #   run: make publish
      #   env:
      #     NEXUS_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     NEXUS_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      #     signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
      #     signing.password: ${{ secrets.SIGNING_PASSWORD }}